version: "4"
name: hospital-service-app-db
services:
  postgres:
    image: postgres
    container_name: hospital-service-db-pg
    restart: unless-stopped
    ports:
      - 8093:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=main
    logging:
      driver: none
    volumes:
      - hospital-service-pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:8.3
    container_name: hospital-service-db-pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - 8094:80
    volumes:
      - hospital-service-pgadmin-data:/var/lib/pgadmin

  activemq-artemis:
    image: apache/activemq-artemis:latest-alpine
    container_name: activemq-artemis
    ports:
      - 61616:61616
      - 8161:8161
    volumes:
      - activemq-artemis-data:/var/lib/artemis-instance

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus

volumes:
  hospital-service-pgdata:
  hospital-service-pgadmin-data:
  activemq-artemis-data:
  prometheus-data:
  grafana-data:
