version: "3"
services:
  backend:
    build:
      context: .
    depends_on:
      - postgres
      - pgadmin
    container_name: hospital-service
    image: hospital-service
    restart: no
    ports:
      - 8092:8092

  postgres:
    image: postgres
    container_name: hospital-service-pg
    restart: unless-stopped
    ports:
      - 8093:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=main
    logging:
      driver: none
    volumes:
      - hospital-service-pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:8.3
    container_name: hospital-service-pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - 8094:80
    volumes:
      - hospital-service-pgadmin-data:/var/lib/pgadmin

volumes:
  hospital-service-pgdata:
  hospital-service-pgadmin-data:
