version: "3"
name: hospital-service-app-db
services:
  activemq-artemis:
    image: apache/activemq-artemis:latest-alpine
    container_name: activemq-artemis
    ports:
      - 61616:61616
      - 8161:8161
    volumes:
      - activemq-artemis-data:/var/lib/artemis-instance

volumes:
  activemq-artemis-data:
