global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'hospital-app'
    scrape_interval: 5s
    static_configs:
      - targets:
          - 'localhost:8081'
          - 'localhost:8082'
          - 'localhost:8090'
          - 'localhost:8092'
