server:
  port: 8092

spring:
  application:
    name: HospitalApp
  thymeleaf:
    mode: HTML
  profiles:
    active: dev
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
  devtools:
    restart:
      enabled: true

springdoc:
  swagger-ui:
    path: /swagger.html
  api-docs:
    path: /swagger-json

app:
  access-token-lifetime: 12000
  refresh-token-lifetime: 24000