###
POST http://localhost:8092/api/auth/login
Content-Type: application/json

{
  "email": "andrew@gmail.com",
  "password": ""
}

###
GET http://localhost:8092/api/patient/1/prescriptions
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhbmRyZXdAZ21haWwuY29tIiwiaWF0IjoxNzAxOTcxMzE2LCJleHAiOjE3MDE5ODMzMTZ9.1ZnwPeI6WILRWwdR1NZWCJftvcIgte814aJLyTYOz9M

###
PUT http://localhost:8092/api/patient/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJwYXRpZW50MUBnbWFpbC5jb20iLCJpYXQiOjE3MDIyMTgxMDcsImV4cCI6MTcwMjIzMDEwN30.og9LV0BE1vlt6q3ePo4mklt10ECkqZ3_V9VOuF8d4Bk

{
  "email": "andrew@gmail.com",
  "firstName": "Andrew",
  "lastName": "Tate",
  "address": "some address",
  "passportNumber": "YU654321",
  "birthDate": "1980-01-01"
}

###
DELETE http://localhost:8092/api/prescription/1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhbmRyZXdAZ21haWwuY29tIiwiaWF0IjoxNzAxOTcxMzE2LCJleHAiOjE3MDE5ODMzMTZ9.1ZnwPeI6WILRWwdR1NZWCJftvcIgte814aJLyTYOz9M

###
