name: Java CI with Gradle. Deploy on Google Cloud

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'    
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - name: Build and test
      run: ./gradlew build
  deploy:
      runs-on: ubuntu-latest
      needs: build
      steps:
      - name: Install ssh client
        run: |
          sudo apt-get update
          sudo apt-get install -y ssh
      - name: Copy SSH private key
        run: ls -a
