# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle. Deploy on Google Cloud

on:
  pull_request:
    branches: [ "deploy" ]
  push:
    branches: [ "deploy" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'    
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - name: Build and test
      run: |
        sudo chmod +x gradlew
        sudo ./gradlew build --refresh-dependencies
  deploy:
      runs-on: ubuntu-latest
      needs: build
      steps:
      - name: Install ssh client
        run: |
          sudo apt-get update
          sudo apt-get install -y ssh
      - name: Copy SSH private key
        run: sudo ls -a ./build/libs/
