# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle. Deploy on Google Cloud

on:
  pull_request:
    branches: [ "deploy" ]
  push:
    branches: [ "deploy" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Set up JDK 11 for x64
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        architecture: x64
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - name: Build and test
      run: sudo gradle build -Dorg.gradle.java.home=/$JAVA_HOME
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: application
        path: ./build/libs/HospitalApp-0.0.1-SNAPSHOT.jar
        retention-days: 5
  deploy:
      runs-on: ubuntu-latest
      needs: build
      steps:
      - name: Download JAR
        uses: actions/download-artifact@v3
        with:
          name: application
      - name: Install ssh client
        run: |
          sudo apt-get update
          sudo apt-get install -y ssh
      - name: Copy SSH key
        run: |
          sudo mkdir -p ~/.ssh
          sudo touch ~/.ssh/id_rsa
          sudo echo "${{ secrets.SSH_SECRET }}" | sudo tee ~/.ssh/id_rsa
      - name: Delete previous jar 
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.HOST }} "sudo pkill -f 'java -jar'"
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.HOST }} "sudo rm ~/*.jar -f"
      - name: Deploy new jar
        run: scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa HospitalApp-0.0.1-SNAPSHOT.jar ${{ secrets.HOST }}:~/
      - name: Start application
        run: ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.HOST }} "sudo java -jar ~/HospitalApp-0.0.1-SNAPSHOT.jar"


          
